// Full studio style list (merged into content/studio-styles.json after the backend branch lands).
// `prompt` is server-only. Occasion styles avoid flags and writing: models garble flag emblems and
// Arabic text, and the Saudi flag carries the Shahada.
export const styles = [
  { id: "white", name: { ar: "أبيض نظيف", en: "Clean white" }, emoji: "⚪", swatch: "#F5F5F5", occasion: null,
    prompt: "Place the product on a seamless pure white studio background with soft, even, diffused lighting and a gentle natural contact shadow beneath it, like a premium online-store catalog photo." },
  { id: "marble", name: { ar: "رخام", en: "Marble" }, emoji: "🤍", swatch: "#E8E4DF", occasion: null,
    prompt: "Place the product on a polished white Carrara marble countertop with soft morning window light from the side and a bright, softly blurred modern kitchen in the background." },
  { id: "pastel", name: { ar: "باستيل ناعم", en: "Soft pastel" }, emoji: "🎀", swatch: "#F8BBD0", occasion: null,
    prompt: "Place the product on a smooth matte surface in soft pastel pink against a pastel peach backdrop, with gentle diffused light and a few small out-of-focus pastel decorations at the edges; dreamy and cheerful." },
  { id: "wood", name: { ar: "خشب دافئ", en: "Warm wood" }, emoji: "🪵", swatch: "#A1887F", occasion: null,
    prompt: "Place the product on a rustic light oak table in warm late-afternoon sunlight, with a linen napkin and a few natural ingredients softly blurred in the background; a cozy homemade feel." },
  { id: "flatlay_flowers", name: { ar: "ورد", en: "Flowers" }, emoji: "🌸", swatch: "#F48FB1", occasion: null,
    prompt: "Place the product on a soft cream linen surface framed at the edges by fresh pink roses, baby's breath and green eucalyptus leaves, in bright soft daylight." },
  { id: "dark_luxury", name: { ar: "فخم داكن", en: "Dark luxury" }, emoji: "🖤", swatch: "#212121", occasion: null,
    prompt: "Place the product on a dark slate surface against a deep charcoal backdrop with dramatic soft side lighting, subtle gold accents and a few elegant blurred gold bokeh lights; a luxurious premium mood." },
  { id: "teachers_day", name: { ar: "يوم المعلم", en: "Teachers' Day" }, emoji: "🍎", swatch: "#E4572E", occasion: "teachers_day",
    prompt: "Place the product on a light wooden school desk with a shiny red apple, a few colorful pencils, a small stack of books and a blank mini chalkboard softly blurred beside it, in bright cheerful classroom daylight. The chalkboard stays blank." },
  { id: "national_day_bh", name: { ar: "العيد الوطني البحريني", en: "Bahrain National Day" }, emoji: "🇧🇭", swatch: "#CE1126", occasion: "national_day",
    prompt: "Place the product on a clean white table with a festive national-day mood: red and white ribbons, red and white balloons and bunting softly blurred in the background, bright daylight. Only red and white decorations; no flags." },
  { id: "national_day_sa", name: { ar: "اليوم الوطني السعودي", en: "Saudi National Day" }, emoji: "🇸🇦", swatch: "#006C35", occasion: "national_day",
    prompt: "Place the product on a clean white table with a festive national-day mood: green and white ribbons, green and white balloons and palm-frond decorations softly blurred in the background, bright daylight. Only green and white decorations; no flags." },
  { id: "national_day_ae", name: { ar: "عيد الاتحاد", en: "UAE National Day" }, emoji: "🇦🇪", swatch: "#00732F", occasion: "national_day",
    prompt: "Place the product on a clean white table with a festive national-day mood: red, green, white and black ribbons and balloons softly blurred in the background, bright daylight. No flags." },
  { id: "national_day_kw", name: { ar: "الأعياد الوطنية الكويتية", en: "Kuwait National Days" }, emoji: "🇰🇼", swatch: "#007A3D", occasion: "national_day",
    prompt: "Place the product on a clean white table with a festive national-day mood: green, white, red and black ribbons and balloons softly blurred in the background, bright daylight. No flags." },
  { id: "national_day_qa", name: { ar: "اليوم الوطني القطري", en: "Qatar National Day" }, emoji: "🇶🇦", swatch: "#8A1538", occasion: "national_day",
    prompt: "Place the product on a clean white table with a festive national-day mood: maroon and white ribbons, maroon and white balloons and bunting softly blurred in the background, bright daylight. No flags." },
  { id: "national_day_om", name: { ar: "العيد الوطني العُماني", en: "Oman National Day" }, emoji: "🇴🇲", swatch: "#DB161B", occasion: "national_day",
    prompt: "Place the product on a clean white table with a festive national-day mood: red, white and green ribbons and balloons softly blurred in the background, bright daylight. No flags." },
  { id: "ramadan", name: { ar: "رمضان", en: "Ramadan" }, emoji: "🌙", swatch: "#1B4F72", occasion: "ramadan",
    prompt: "Place the product on a dark wooden table set for a Ramadan evening: warm glowing brass lanterns and a golden crescent-moon ornament softly blurred in the background, a small bowl of dates at the side, warm golden light; elegant and cozy." },
  { id: "eid", name: { ar: "العيد", en: "Eid" }, emoji: "✨", swatch: "#7B2CBF", occasion: "eid",
    prompt: "Place the product on an elegant table decorated for Eid: cream and gold tones, delicate gold crescent and star ornaments and warm fairy lights softly blurred in the background, a few wrapped gift boxes at the side, bright festive light." },
  { id: "gergaoun", name: { ar: "قرقاعون", en: "Gergaoun" }, emoji: "🍬", swatch: "#F2A900", occasion: "gergaoun",
    prompt: "Place the product on a festive table for the Gulf mid-Ramadan children's celebration: colorful traditional woven baskets and small cloth bags filled with wrapped candies and nuts softly blurred around it, cheerful bright colors, warm evening light." },
  { id: "valentines", name: { ar: "يوم الحب", en: "Valentine's" }, emoji: "❤️", swatch: "#D7263D", occasion: "valentines",
    prompt: "Place the product on a white table scattered with red rose petals, with red roses and soft heart-shaped bokeh lights blurred in the background, in warm romantic light." },
  { id: "mothers_day", name: { ar: "عيد الأم", en: "Mother's Day" }, emoji: "💐", swatch: "#E91E63", occasion: "mothers_day",
    prompt: "Place the product on a soft blush-pink table next to a bouquet of pink peonies and roses and a small blank greeting card, in bright soft morning light; tender and elegant. The card stays blank." },
  { id: "graduation", name: { ar: "التخرج", en: "Graduation" }, emoji: "🎓", swatch: "#1A237E", occasion: "graduation",
    prompt: "Place the product on a table with a navy and gold graduation theme: a black graduation cap, a rolled diploma tied with a gold ribbon and gold confetti softly blurred around it, bright celebratory light." },
  { id: "back_to_school", name: { ar: "المدارس", en: "Back to school" }, emoji: "🎒", swatch: "#F57C00", occasion: "back_to_school",
    prompt: "Place the product on a bright table with colorful pencils, a notebook, a small kids' lunchbox and a red apple softly blurred around it, in cheerful morning light." },
  { id: "new_year", name: { ar: "رأس السنة", en: "New Year" }, emoji: "🎉", swatch: "#B8860B", occasion: "new_year",
    prompt: "Place the product on a dark table with gold confetti, glowing sparklers and warm gold bokeh lights in the background; a festive night-party mood. No drinks." },
];
